### PR TITLE
fix(meeting): updated sdkcomponentadapter version to add password flow

### PR DESCRIPTION
**Pull request by Kesari3008**
Upgrading sdk-component-adpater repo version to the latest to include the password flow for the guest user.

Testcase 1: The guest joins the meeting by entering the password.
Testcase 2: The guest joins the meeting as host by entering the host key

https://github.com/webex/widgets/assets/65543166/381bc96d-d55c-43e4-a411-4150d5e9b68c

Testcase 3: Host joins with host access token without a password prompt.
https://github.com/webex/widgets/assets/65543166/135cf872-4e0c-43e1-a0ec-3317c45ac45d

### CODE REVIEW

**Review by sreenara — APPROVED** [review]
Changes look good.
Any reason why the Video is disabled while joining the meeting? The console seemed to show some error to get the stream.

**Comment by Kesari3008** [comment]
> Changes look good. Any reason why the Video is disabled while joining the meeting? The console seemed to show some error to get the stream.

@sreenara I disabled the video that's why

**Comment by Neeraj-swarnkar** [comment]
@Kesari3008, Also I don't see package.lock file change ? Did you do npm install after upgrade.

**Pull request merged**
